# **CAPSTONE DEFENSE PROJECT**
# **POWER BI** 

### **Business Understanding**

### 1. Project Description/Background

The objective of this Power BI Dashboard project is to transform the raw transactional data collected by the client in the year 2019 into actionable insights. By leveraging business intelligence tools, we aim to empower our client to make informed decisions to drive sales and enhance operational efficiency.

**Objective:**

The primary objective of this Power BI Dashboard project is to leverage the collected transactional data from the year 2019 to provide actionable insights for our client. Specifically, the objective encompasses the following key points:

1. Revenue Analysis: Determine the total revenue generated throughout the year 2019, providing a clear understanding of the financial performance over the specified period.

2. Seasonality Assessment: Identify any recurring patterns or seasonality in sales data to facilitate better resource allocation, inventory management, and marketing strategies.

3. Product Performance Evaluation: Analyze sales data to identify the best-selling and worst-selling products, enabling the optimization of product offerings and inventory management practices.

4. Sales Trend Analysis: Compare sales performance across different time periods (months or weeks) to identify trends, fluctuations, and potential areas for improvement or expansion.

5. Geographical Insights: Determine the distribution of product deliveries across various cities to enable targeted marketing efforts and optimize logistics operations.

6. Product Category Comparison: Compare revenue generated and quantities ordered across different product categories, providing insights into the performance of various product lines and guiding future product development strategies.

7. Additional Details Integration: Incorporate additional details from the data findings to provide a comprehensive understanding of business performance, including the classification of products into high-level and basic categories based on unit prices.

By achieving these objectives, the Power BI Dashboard will empower our client to make data-driven decisions, enhance sales strategies, optimize operations, and drive overall business growth and efficiency.

#### 2. Features

The dataset provided contains the following fields:

1. Order ID: Unique identifier for each order placed.
2. Product: Name or description of the product purchased.
4. Quantity Ordered: The number of units of the product ordered in each transaction.
5. Price Each: The unit price of the product.
6. Order Date: Date and time when the order was placed.
7. Purchase Address: Address where the purchase was made or where the products were delivered.

**The Hypothesis**

  **Null Hypothesis:** There is no difference in revenue generated between different product categories.
  
  **Alternative Hypothesis:** Certain product categories generate significantly more revenue compared to others.

**The Analytical Questions**

1. How much money did we make this year? 

2. Can we identify any seasonality in the  sales? 

3. What are our best and worst-selling products? 

4. How do sales compare to previous months or weeks? 

5. Which cities are our products delivered to most? 

6. How do product categories compare in revenue generated and quantities  ordered? 

7. What are the best and worst-selling products?

### Data Understanding

### Data Analysis and Hypothesis Testing

In [7]:
# Data manipulation packages
import pyodbc
from scipy.stats import f_oneway
from sqlalchemy import create_engine
from dotenv import dotenv_values
import pandas as pd
import numpy as np

#Data visualization packages
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

Loading data Sales January, February, March, April, May, June 2019

Loading Data from SQL Server for July - December 2019

In [8]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values('.env')

In [9]:
# Get the values for the credentials you set in the '.env' file
server = environment_variables.get("SERVER")
database = environment_variables.get("DATABASE")
username = environment_variables.get("UID")
password = environment_variables.get("PWD")

In [10]:
# Define connection string with appropriate parameters

connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}"

In [13]:
# Establish a connection to the database using the provided connection string.
connection= pyodbc.connect(connection_string)

In [ ]:
df_sales_January_2019 = pd.read_csv('Power BI Capstione Data - (Jan -May)/Sales_January_2019.csv')

# Display the first few rows of the DataFrame
df_sales_January_2019.head()

In [14]:
df_sales_February_2019 = pd.read_csv('Power BI Capstione Data - (Jan -May)/Sales_February_2019.csv')
# Display the first few rows of the DataFrame
df_sales_February_2019.head()

Order ID                   Product Quantity Ordered Price Each  \
0   150502                    iPhone                1        700   
1   150503     AA Batteries (4-pack)                1       3.84   
2   150504    27in 4K Gaming Monitor                1     389.99   
3   150505  Lightning Charging Cable                1      14.95   
4   150506     AA Batteries (4-pack)                2       3.84   

       Order Date                     Purchase Address  
0  02/18/19 01:35    866 Spruce St, Portland, ME 04101  
1  02/13/19 07:24  18 13th St, San Francisco, CA 94016  
2  02/18/19 09:46   52 6th St, New York City, NY 10001  
3  02/02/19 16:47     129 Cherry St, Atlanta, GA 30301  
4  02/28/19 20:32    548 Lincoln St, Seattle, WA 98101

In [15]:
df_sales_March_2019 = pd.read_csv('Power BI Capstione Data - (Jan -May)/Sales_March_2019.csv')

# Display the first few rows of the DataFrame
df_sales_March_2019.head()

Order ID                     Product Quantity Ordered Price Each  \
0   162009                      iPhone                1        700   
1   162009    Lightning Charging Cable                1      14.95   
2   162009            Wired Headphones                2      11.99   
3   162010  Bose SoundSport Headphones                1      99.99   
4   162011      34in Ultrawide Monitor                1     379.99   

       Order Date                      Purchase Address  
0  03/28/19 20:59       942 Church St, Austin, TX 73301  
1  03/28/19 20:59       942 Church St, Austin, TX 73301  
2  03/28/19 20:59       942 Church St, Austin, TX 73301  
3  03/17/19 05:39  261 10th St, San Francisco, CA 94016  
4  03/10/19 00:01  764 13th St, San Francisco, CA 94016

In [16]:
df_sales_April_2019 = pd.read_csv('Power BI Capstione Data - (Jan -May)/Sales_April_2019.csv')

# Display the first few rows of the DataFrame
df_sales_April_2019.head()

Order ID                     Product Quantity Ordered Price Each  \
0   176558        USB-C Charging Cable                2      11.95   
1      NaN                         NaN              NaN        NaN   
2   176559  Bose SoundSport Headphones                1      99.99   
3   176560                Google Phone                1        600   
4   176560            Wired Headphones                1      11.99   

       Order Date                      Purchase Address  
0  04/19/19 08:46          917 1st St, Dallas, TX 75001  
1             NaN                                   NaN  
2  04/07/19 22:30     682 Chestnut St, Boston, MA 02215  
3  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001  
4  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001

In [17]:
df_sales_May_2019 = pd.read_csv('Power BI Capstione Data - (Jan -May)/Sales_May_2019.csv')

# Display the first few rows of the DataFrame
df_sales_May_2019.head()

Order ID                 Product Quantity Ordered Price Each  \
0   194095        Wired Headphones                1      11.99   
1   194096   AA Batteries (4-pack)                1       3.84   
2   194097        27in FHD Monitor                1     149.99   
3   194098        Wired Headphones                1      11.99   
4   194099  AAA Batteries (4-pack)                2       2.99   

       Order Date                         Purchase Address  
0  05/16/19 17:14      669 2nd St, New York City, NY 10001  
1  05/19/19 14:43          844 Walnut St, Dallas, TX 75001  
2  05/24/19 11:36  164 Madison St, New York City, NY 10001  
3  05/02/19 20:40          622 Meadow St, Dallas, TX 75001  
4  05/11/19 22:55          17 Church St, Seattle, WA 98101

In [18]:
df_sales_June_2019 = pd.read_csv('Power BI Capstione Data - (Jan -May)/Sales_June_2019.csv')

# Display the first few rows of the DataFrame
df_sales_June_2019.head()

Order ID                     Product Quantity Ordered Price Each  \
0   209921        USB-C Charging Cable                1      11.95   
1   209922          Macbook Pro Laptop                1     1700.0   
2   209923             ThinkPad Laptop                1     999.99   
3   209924            27in FHD Monitor                1     149.99   
4   209925  Bose SoundSport Headphones                1      99.99   

       Order Date                       Purchase Address  
0  06/23/19 19:34      950 Walnut St, Portland, ME 04101  
1  06/30/19 10:05     80 4th St, San Francisco, CA 94016  
2  06/24/19 20:18  402 Jackson St, Los Angeles, CA 90001  
3  06/05/19 10:21         560 10th St, Seattle, WA 98101  
4  06/25/19 18:58    545 2nd St, San Francisco, CA 94016

In [19]:
# SQL query to fetch data from 'dbo.LP1_startup_funding2020' table
query = "Select * from dbo.Sales_July_2019"

# Read data from the SQL query result
dap_july = pd.read_sql(query, connection)

# Display the first few rows of the DataFrame
dap_july.head()


C:\Users\Sami\AppData\Local\Temp\ipykernel_3344\3596020920.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dap_july = pd.read_sql(query, connection)


Order_ID                   Product  Quantity_Ordered  Price_Each  \
0  222910.0  Apple Airpods Headphones               1.0      150.00   
1  222911.0             Flatscreen TV               1.0      300.00   
2  222912.0     AA Batteries (4-pack)               1.0        3.84   
3  222913.0     AA Batteries (4-pack)               1.0        3.84   
4  222914.0    AAA Batteries (4-pack)               5.0        2.99   

                    Order_Date                  Purchase_Address  
0  2026-07-19 16:51:00.0000000   389 South St, Atlanta, GA 30301  
1  2005-07-19 08:55:00.0000000     590 4th St, Seattle, WA 98101  
2  2029-07-19 12:41:00.0000000    861 Hill St, Atlanta, GA 30301  
3  2028-07-19 10:15:00.0000000   190 Ridge St, Atlanta, GA 30301  
4  2031-07-19 02:13:00.0000000  824 Forest St, Seattle, WA 98101

In [21]:
query = "Select * from dbo.Sales_August_2019"

dap_august = pd.read_sql(query, connection)

dap_august.head()


C:\Users\Sami\AppData\Local\Temp\ipykernel_3344\949500391.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dap_august = pd.read_sql(query, connection)


Order_ID                     Product  Quantity_Ordered  Price_Each  \
0  236670.0            Wired Headphones               2.0   11.990000   
1  236671.0  Bose SoundSport Headphones               1.0   99.989998   
2  236672.0                      iPhone               1.0  700.000000   
3  236673.0       AA Batteries (4-pack)               2.0    3.840000   
4  236674.0       AA Batteries (4-pack)               2.0    3.840000   

                    Order_Date                      Purchase_Address  
0  2031-08-19 22:21:00.0000000      359 Spruce St, Seattle, WA 98101  
1  2015-08-19 15:11:00.0000000        492 Ridge St, Dallas, TX 75001  
2  2006-08-19 14:40:00.0000000        149 7th St, Portland, OR 97035  
3  2029-08-19 20:59:00.0000000     631 2nd St, Los Angeles, CA 90001  
4  2015-08-19 19:53:00.0000000  736 14th St, New York City, NY 10001

In [20]:
query= "Select * from dbo.Sales_September_2019"

dap_sept = pd.read_sql(query, connection)

dap_sept.head()



C:\Users\Sami\AppData\Local\Temp\ipykernel_3344\4226239043.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dap_sept = pd.read_sql(query, connection)


Order_ID                Product  Quantity_Ordered  Price_Each  \
0  248151.0  AA Batteries (4-pack)               4.0    3.840000   
1  248152.0   USB-C Charging Cable               2.0   11.950000   
2  248153.0   USB-C Charging Cable               1.0   11.950000   
3  248154.0       27in FHD Monitor               1.0  149.990005   
4  248155.0   USB-C Charging Cable               1.0   11.950000   

                    Order_Date                       Purchase_Address  
0  2017-09-19 14:44:00.0000000    380 North St, Los Angeles, CA 90001  
1  2029-09-19 10:19:00.0000000           511 8th St, Austin, TX 73301  
2  2016-09-19 17:48:00.0000000  151 Johnson St, Los Angeles, CA 90001  
3  2027-09-19 07:52:00.0000000      355 Hickory St, Seattle, WA 98101  
4  2001-09-19 19:03:00.0000000          125 5th St, Atlanta, GA 30301

In [22]:
query= "Select * from dbo.Sales_October_2019"

dap_oct = pd.read_sql(query, connection)

dap_oct.head()



C:\Users\Sami\AppData\Local\Temp\ipykernel_3344\2242588360.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dap_oct = pd.read_sql(query, connection)


Order_ID                 Product  Quantity_Ordered  Price_Each  \
0  259358.0  34in Ultrawide Monitor               1.0  379.989990   
1  259359.0  27in 4K Gaming Monitor               1.0  389.989990   
2  259360.0  AAA Batteries (4-pack)               2.0    2.990000   
3  259361.0        27in FHD Monitor               1.0  149.990005   
4  259362.0        Wired Headphones               1.0   11.990000   

                    Order_Date                           Purchase_Address  
0  2028-10-19 10:56:00.0000000            609 Cherry St, Dallas, TX 75001  
1  2028-10-19 17:26:00.0000000          225 5th St, Los Angeles, CA 90001  
2  2024-10-19 17:20:00.0000000       967 12th St, New York City, NY 10001  
3  2014-10-19 22:26:00.0000000  628 Jefferson St, New York City, NY 10001  
4  2007-10-19 16:10:00.0000000         534 14th St, Los Angeles, CA 90001

In [23]:

query = "Select * from dbo.Sales_November_2019"

dap_nov = pd.read_sql(query, connection)

dap_nov.head()



C:\Users\Sami\AppData\Local\Temp\ipykernel_3344\126429497.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dap_nov = pd.read_sql(query, connection)


Order_ID                     Product  Quantity_Ordered  Price_Each  \
0  278797.0            Wired Headphones               1.0   11.990000   
1  278798.0        USB-C Charging Cable               2.0   11.950000   
2  278799.0    Apple Airpods Headphones               1.0  150.000000   
3  278800.0            27in FHD Monitor               1.0  149.990005   
4  278801.0  Bose SoundSport Headphones               1.0   99.989998   

                    Order_Date                      Purchase_Address  
0  2021-11-19 09:54:00.0000000   46 Park St, New York City, NY 10001  
1  2017-11-19 10:03:00.0000000      962 Hickory St, Austin, TX 73301  
2  2019-11-19 14:56:00.0000000  464 Cherry St, Los Angeles, CA 90001  
3  2025-11-19 22:24:00.0000000        649 10th St, Seattle, WA 98101  
4  2009-11-19 13:56:00.0000000         522 Hill St, Boston, MA 02215

In [ ]:
query = "Select * from dbo.Sales_December_2019"

dap_dec = pd.read_sql(query, connection)

dap_dec.head()

### Exploratory Data Analysis

JANUARY 2019

In [ ]:
df_sales_January_2019.info()

In [ ]:
df_sales_January_2019.columns

In [ ]:
df_sales_January_2019.duplicated().sum()

 There are 50 duplicate rows in the DataFrame df_sales_January_2019. Duplicate rows may indicate errors in data collection or entry and may need to be investigated further to ensure data quality.

In [ ]:
# Checking missing values for First dataset
df_sales_January_2019.isnull().sum()



In [ ]:
# Descriptive statistics
df_sales_January_2019.describe()

The DataFrame df_sales_January_2019 contains sales data for January 2019. Here's a summary of its descriptive statistics:

1. Order ID: There are 9697 entries. However, there are 9269 unique Order IDs, indicating some duplication or inconsistency. The most frequent entry is "Order ID" with a frequency of 16, suggesting potential header repetition or missing values.
2. Product: There are 9697 entries and 20 unique products. The most common product is the "USB-C Charging Cable" with a frequency of 1171, indicating its popularity among customers.
3. Quantity Ordered: There are 9697 entries, and the quantity ordered ranges from 1 to 8 units. The most common quantity ordered is 1, occurring 8795 times.
4. Price Each: There are 9697 entries, and the price of each item ranges from $2.99 to $1700. The most common price is $11.95, occurring 1171 times.
5. Order Date: There are 9697 entries, and 8077 unique order dates. The most frequent entry is "Order Date" with a frequency of 16, indicating potential inconsistency or repetition.
6. Purchase Address: There are 9697 entries, and 9161 unique purchase addresses. The most frequent entry is "Purchase Address" with a frequency of 16, indicating potential inconsistency or repetition.

Overall, the summary suggests that there may be inconsistencies and missing values in the dataset, particularly in the "Order ID" and "Order Date" columns. Cleaning and preprocessing may be necessary before further analysis.

In [ ]:
completely_empty_rows = df_sales_January_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

FEBRUARY 2019

In [ ]:
df_sales_February_2019.info()

In [ ]:
df_sales_February_2019.columns

In [ ]:
df_sales_February_2019.duplicated().sum()

In the DataFrame for February 2019 sales (df_sales_February_2019), there are 66 duplicate rows. These duplicates might indicate errors in data entry or repeated transactions, and they should be reviewed and potentially removed to ensure the accuracy of the dataset for analysis.

In [ ]:
# Checking missing values for First dataset
df_sales_February_2019.isnull().sum()


In the dataset for February 2019 sales (df_sales_February_2019), each column contains 32 missing values. This suggests potential data entry issues or gaps in the data collection process for that month. These missing values need to be addressed to ensure the integrity and completeness of the dataset for analysis.

In [ ]:
# Descriptive statistics
df_sales_February_2019.describe()

1. Order ID: There are 12004 entries. However, there are 11508 unique Order IDs, indicating some duplication or inconsistency. The most frequent entry is "Order ID" with a frequency of 18, suggesting potential header repetition or missing values.
2. Product: There are 12004 entries and 20 unique products. The most common product is the "USB-C Charging Cable" with a frequency of 1514, indicating its popularity among customers.
3. Quantity Ordered: There are 12004 entries, and the quantity ordered ranges from 1 to 8 units. The most common quantity ordered is 1, occurring 10863 times.
4. Price Each: There are 12004 entries, and the price of each item ranges from $2.99 to $1700. The most common price is $11.95, occurring 1514 times.
5. Order Date: There are 12004 entries, and 9627 unique order dates. The most frequent entry is "Order Date" with a frequency of 18, indicating potential inconsistency or repetition.
6. Purchase Address: There are 12004 entries, and 11316 unique purchase addresses. The most frequent entry is "Purchase Address" with a frequency of 18, indicating potential inconsistency or repetition.
Similarly to the previous summary, there may be inconsistencies and missing values in the dataset, particularly in the "Order ID" and "Order Date" columns. Cleaning and preprocessing may be necessary before further analysis.

In [ ]:
completely_empty_rows = df_sales_February_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

MARCH 2019

In [ ]:
df_sales_March_2019.info()

In [ ]:
df_sales_March_2019.columns

In [ ]:
df_sales_March_2019.duplicated().sum()

The number of duplicate rows in the DataFrame for March 2019 sales (df_sales_March_2019) is 95.

In [ ]:
# Checking missing values for First dataset
df_sales_March_2019.isnull().sum()


In the DataFrame for March 2019 sales (df_sales_March_2019), there are 37 missing values in each column: Order ID, Product, Quantity Ordered, Price Each, Order Date, and Purchase Address. These missing values need to be handled appropriately before further analysis or processing.

In [ ]:
# Descriptive statistics
df_sales_March_2019.describe()

In the DataFrame for March 2019 sales (df_sales_March_2019), the descriptive statistics are as follows:

1. Order ID: There are 15,189 entries. The number of unique order IDs is 14,550. The top value is "Order ID," occurring 35 times.
Product: There are 15,189 entries. The number of unique products is 20. The most frequent product is "USB-C Charging Cable," occurring 1,770 times.
2. Quantity Ordered: There are 15,189 entries. The number of unique quantities ordered is 8. The most frequent quantity ordered is 1, occurring 13,779 times.
3. Price Each: There are 15,189 entries. The number of unique prices is 19. The top price is $11.95, occurring 1,770 times.
Order Date: There are 15,189 entries. The number of unique order dates is 11,784. The top value is "Order Date," occurring 35 times.
4. Purchase Address: There are 15,189 entries. The number of unique purchase addresses is 14,247. The top value is "Purchase Address," occurring 35 times.
These statistics provide an overview of the data distribution and can help identify any anomalies or inconsistencies in the dataset.

In [ ]:
completely_empty_rows = df_sales_March_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

APRIL 2019

In [ ]:
df_sales_April_2019.info()

In [ ]:
df_sales_April_2019.columns

In [ ]:
df_sales_April_2019.duplicated().sum()


There are 114 duplicate rows in the April 2019 sales data DataFrame.

In [ ]:
# Checking missing values for First dataset
df_sales_April_2019.isnull().sum()


The April 2019 sales data has 59 missing values in each of the columns: 'Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date', and 'Purchase Address'.

In [ ]:
# Descriptive statistics
df_sales_April_2019.describe()

The summary statistics for the April 2019 sales data are as follows:

1. Order ID: There are 18,324 entries. The number of unique order IDs is 17,538. The most frequent entry is "Order ID" with a frequency of 35.
2. Product: There are 18,324 entries. There are 20 unique products. The most frequent product is "Lightning Charging Cable" with a frequency of 2,201.
3. Quantity Ordered: There are 18,324 entries. There are 8 unique quantities ordered. The most frequent quantity ordered is 1, with a frequency of 16,558.
4. Price Each: There are 18,324 entries. There are 19 unique prices. The most frequent price is $14.95, with a frequency of 2,201.
5. Order Date: There are 18,324 entries. There are 13,584 unique order dates. The most frequent entry is "Order Date" with a frequency of 35.
6. Purchase Address: There are 18,324 entries. There are 17,120 unique purchase addresses. The most frequent entry is "Purchase Address" with a frequency of 35.

In [ ]:
completely_empty_rows = df_sales_April_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

MAY 2019

In [ ]:
df_sales_May_2019.info()

In [ ]:
df_sales_May_2019.columns

In [ ]:
df_sales_May_2019.duplicated().sum()

In the May 2019 sales data, there are 93 duplicate rows.

In [ ]:
# Checking missing values for First dataset
df_sales_May_2019.isnull().sum()


In the May 2019 sales data, there are 48 missing values in each of the following columns: 'Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date', and 'Purchase Address'.

In [ ]:
# Descriptive statistics
df_sales_May_2019.describe()

The descriptive statistics of the May 2019 sales data indicate that:

There are 16,587 records in the DataFrame.
1. The 'Order ID' column has 15,827 unique values, indicating some duplication in this column.
2. The 'Product' column has 20 unique values.
3. The 'Quantity Ordered' column has 8 unique values.
4. The 'Price Each' column has 22 unique values.
5. The 'Order Date' column has 12,665 unique values, suggesting variability in the order dates.
6. The 'Purchase Address' column has 15,461 unique values.
The most frequent value in the 'Product' column is 'Lightning Charging Cable', with 1,932 occurrences.
The most frequent value in the 'Quantity Ordered' column is '1', with 14,977 occurrences.
The most frequent value in the 'Price Each' column is '14.95', with 1,932 occurrences.
The most frequent value in the 'Order Date' column is 'Order Date', with 33 occurrences.
The most frequent value in the 'Purchase Address' column is 'Purchase Address', with 33 occurrences.

In [ ]:
completely_empty_rows = df_sales_May_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

JUNE 2019

In [ ]:
df_sales_June_2019.info()

In [ ]:
df_sales_June_2019.columns

In [ ]:
df_sales_June_2019.duplicated().sum()

There are 83 duplicate rows in the June 2019 sales data DataFrame.

In [ ]:
# Checking missing values for First dataset
df_sales_June_2019.isnull().sum()


In the June 2019 sales data, there are 43 missing values in each of the following columns: Order ID, Product, Quantity Ordered, Price Each, Order Date, and Purchase Address.

In [ ]:
# Descriptive statistics
df_sales_June_2019.describe()


In the June 2019 sales data:

1. The Order ID column has 23 occurrences of the top value "Order ID".
2. The Product column has 20 unique values.
3. The Quantity Ordered column has 8 unique values.
4. The Price Each column has 23 unique values.
5. The Order Date column has 10,742 unique values.
6. The Purchase Address column has 12,720 unique values.

In [ ]:
completely_empty_rows = df_sales_June_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

JULY 2019

In [ ]:
dap_july.info()

In [ ]:
dap_july.columns

In [ ]:
dap_july.duplicated().sum()

In July, there are 96 duplicate rows in the DataFrame.

In [ ]:
# Checking missing values for First dataset
dap_july.isnull().sum()


In July, there are 80 missing values in the 'Order_ID', 'Quantity_Ordered', 'Price_Each', and 'Order_Date' columns. Additionally, there are 45 missing values in the 'Product' and 'Purchase_Address' columns.

In [ ]:
# Descriptive statistics
dap_july.describe()

In July, the sales data indicates the following:

1. Order_ID: The orders range from 222910 to 236669, with an average of around 229788. The standard deviation is approximately 3970.66, suggesting a moderate dispersion around the mean.
2. Quantity_Ordered: On average, each order consists of approximately 1.12 items, with a standard deviation of around 0.46. The minimum quantity ordered is 1, while the maximum is 9.
3. Price_Each: The average price per item sold is approximately $184.15, with a considerable standard deviation of $332.95. Prices range from $2.99 to $1700.00.

In [ ]:
completely_empty_rows = dap_july.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

AUGUST 2019

In [ ]:
dap_august.info()

In [ ]:
dap_august.columns

In [ ]:
dap_august.duplicated().sum()

There are 70 duplicate rows in the DataFrame dap_august.

In [ ]:
# Checking missing values for First dataset
dap_august.isnull().sum()


The DataFrame dap_august has missing values in the following columns:

1. Order_ID: 54 missing values
2. Product: 28 missing values
3. Quantity_Ordered: 54 missing values
4. Price_Each: 54 missing values
5. Order_Date: 54 missing values
6. Purchase_Address: 28 missing values

In [ ]:
# Descriptive statistics
dap_august.describe()

In this summary:

1. The Order_ID, Quantity_Ordered, and Price_Each columns have a count of 11,957 entries each.
2. The mean quantity ordered is approximately 1.12, with a standard deviation of about 0.45.
3. The mean price per item is around $186.53, with a standard deviation of approximately $332.30.
4. The minimum Order_ID is 236,670, and the maximum is 248,150.
5. The minimum quantity ordered is 1, and the maximum is 8.
6. The prices range from $2.99 to $1700.

In [ ]:
completely_empty_rows = dap_august.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

SEPTEMBER 2019

In [ ]:
dap_sept.info()

In [ ]:
dap_sept.columns

In [ ]:
dap_sept.duplicated().sum()

There are 73 duplicate rows in the September dataset.

In [ ]:
# Checking missing values for First dataset
dap_sept.isnull().sum()


The dataset for September contains missing values in multiple columns:

1. Order_ID: There are 57 missing values.
2. Product: There are 40 missing values.
3. Quantity_Ordered: There are 57 missing values.
4. Price_Each: There are 57 missing values.
5. Order_Date: There are 57 missing values.
6. Purchase_Address: There are 40 missing values.

In [ ]:
# Descriptive statistics
dap_sept.describe()

The dataset consists of 11,629 entries.

For the Order_ID column:

1. The minimum order ID is 248,151, and the maximum order ID is 259,357.
The mean order ID is approximately 253,751.81, with a standard deviation of approximately 3,235.18.
The median (50th percentile) order ID is 253,751.
For the Quantity_Ordered column:

2. The minimum quantity ordered is 1, and the maximum quantity ordered is 6.
The mean quantity ordered is approximately 1.13, with a standard deviation of approximately 0.44.
The median (50th percentile) quantity ordered is 1.
For the Price_Each column:

3. The minimum price is $2.99, and the maximum price is $1700.00.
The mean price is approximately $179.40, with a standard deviation of approximately $328.60.
The median (50th percentile) price is $14.95.

In [ ]:
completely_empty_rows = dap_sept.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

OCTOBER 2019

In [ ]:
dap_oct.info()

In [ ]:
dap_oct.columns

In [ ]:
dap_oct.duplicated().sum()

There are 126 duplicate rows in the October DataFrame.

In [ ]:
# Checking missing values for First dataset
dap_oct.isnull().sum()


in the October dataset, there are missing values in several columns:

95 missing values in the 'Order_ID', 'Quantity_Ordered', 'Price_Each', and 'Order_Date' columns.
62 missing values in the 'Product' and 'Purchase_Address' columns.

In [ ]:
# Descriptive statistics
dap_oct.describe()

The October dataset has 20,284 entries. For the 'Order_ID' column, the minimum value is 259,358, and the maximum value is 278,796. The 'Quantity_Ordered' column has a mean of approximately 1.12, with a standard deviation of around 0.44. In the 'Price_Each' column, the mean price is approximately $183.18, with a standard deviation of approximately $334.00.

In [ ]:
completely_empty_rows = dap_oct.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

NOVEMBER 2019

In [ ]:
dap_nov.info()

In [ ]:
dap_nov.columns

In [ ]:
dap_nov.duplicated().sum()

In the November DataFrame, there are 108 duplicate rows.

In [ ]:
# Checking missing values for First dataset
dap_nov.isnull().sum()


in the November DataFrame, there are missing values in several columns:

Order_ID: 81 missing values

Product: 45 missing values

Quantity_Ordered: 81 missing values

Price_Each: 81 missing values

Order_Date: 81 missing values

Purchase_Address: 45 missing values

In [ ]:
# Descriptive statistics
dap_nov.describe()

The November DataFrame consists of 17,580 entries. Here's a summary of its descriptive statistics:

1. Order_ID: Ranges from 278797 to 295664 with a mean of approximately 287,236. The standard deviation is around 4,867, indicating a moderate spread of data around the mean.
2. Quantity_Ordered: The average quantity ordered is about 1.13, with a standard deviation of approximately 0.45. The quantity ranges from 1 to 8 units.
3. Price_Each: Prices range from $2.99 to $1700. The mean price is approximately $180.88, with a standard deviation of about $330. This wide spread indicates considerable variability in item prices.

In [ ]:
completely_empty_rows = dap_nov.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

DECEMBER 2019

In [ ]:
dap_dec.info()

In [ ]:
dap_dec.columns

In [ ]:
dap_dec.duplicated().sum()

In December's dataset, there are 166 duplicate rows.

In [ ]:
# Checking missing values for First dataset
dap_dec.isnull().sum()


In December's dataset:

1. Order_ID: There are 128 missing values.
2. Product: There are 80 missing values.
3. Quantity_Ordered: There are 128 missing values.
4. Price_Each: There are 128 missing values.
5. Order_Date: There are 128 missing values.
6. Purchase_Address: There are 80 missing values.

In [ ]:
# Descriptive statistics
dap_dec.describe()

1. Order_ID: There are 24989 orders in total.
2. Quantity_Ordered: The average quantity ordered is approximately 1.13, with a standard deviation of around 0.45. The minimum quantity ordered is 1, and the maximum is 7.
3. Price_Each: The mean price per item is approximately $183.85, with a standard deviation of approximately $333.08. The prices range from $2.99 to $1700.

In [ ]:
completely_empty_rows = dap_dec.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

### Data Preparation

January

In [ ]:
df_sales_January_2019.dropna(subset=df_sales_January_2019.columns[df_sales_January_2019.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = df_sales_January_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
df_sales_January_2019.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
df_sales_January_2019.drop_duplicates(inplace=True)
df_sales_January_2019.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
df_sales_January_2019.duplicated().sum()

In [ ]:
# Convert 'Order ID' column to numeric, coercing errors to NaN
df_sales_January_2019['Order ID'] = pd.to_numeric(df_sales_January_2019['Order ID'], errors='coerce')

# Convert 'Quantity Ordered' and 'Price Each' columns to numeric
df_sales_January_2019['Quantity Ordered'] = pd.to_numeric(df_sales_January_2019['Quantity Ordered'], errors='coerce')
df_sales_January_2019['Price Each'] = pd.to_numeric(df_sales_January_2019['Price Each'], errors='coerce')

# Convert 'Order Date' column to datetime
df_sales_January_2019['Order Date'] = pd.to_datetime(df_sales_January_2019['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(df_sales_January_2019.dtypes)


In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in df_sales_January_2019.columns:
    unique_values = df_sales_January_2019[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in df_sales_January_2019.columns:
    unique_values = df_sales_January_2019[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)


Observations:

1. Order ID: The 'Order ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. It includes a variety of products such as iPhones, charging cables, headphones, monitors, batteries, laptops, TVs, and washing machines. However, there are two unusual entries: 'nan' and 'Product', which might indicate missing or placeholder values.
3. Quantity Ordered: The 'Quantity Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some unusual entries such as 'nan' and 'Quantity Ordered', which may indicate missing or placeholder values.
4. Price Each: The 'Price Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some unusual entries such as 'nan' and 'Price Each', which may indicate missing or placeholder values. Additionally, there are some duplicate values in a different format ('600' and '600.0').
5. Order Date: The 'Order Date' column contains the date and time when each order was placed. Entries are in the format 'MM/DD/YY HH:mm'.
6. Purchase Address: The 'Purchase Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, and ZIP code.

Overall, while most columns appear to contain relevant information, there are some anomalies in the 'Product', 'Quantity Ordered', and 'Price Each' columns that need further investigation and potential cleaning. Additionally, missing values ('nan') and placeholder values ('Product' and 'Quantity Ordered') should be addressed to ensure the integrity of the dataset.

February

In [ ]:
df_sales_February_2019.dropna(subset=df_sales_February_2019.columns[df_sales_February_2019.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = df_sales_February_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
df_sales_February_2019.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
df_sales_February_2019.drop_duplicates(inplace=True)
df_sales_February_2019.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
df_sales_February_2019.duplicated().sum()

In [ ]:
# Convert 'Order ID' column to numeric, coercing errors to NaN
df_sales_February_2019['Order ID'] = pd.to_numeric(df_sales_February_2019['Order ID'], errors='coerce')

# Convert 'Quantity Ordered' and 'Price Each' columns to numeric
df_sales_February_2019['Quantity Ordered'] = pd.to_numeric(df_sales_February_2019['Quantity Ordered'], errors='coerce')
df_sales_February_2019['Price Each'] = pd.to_numeric(df_sales_February_2019['Price Each'], errors='coerce')

# Convert 'Order Date' column to datetime
df_sales_February_2019['Order Date'] = pd.to_datetime(df_sales_February_2019['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(df_sales_February_2019.dtypes)


In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in df_sales_February_2019.columns:
    unique_values = df_sales_February_2019[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in df_sales_February_2019.columns:
    unique_values = df_sales_February_2019[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)


Observations:

1. Order ID: The 'Order ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. It includes a variety of products such as iPhones, batteries, monitors, charging cables, headphones, laptops, TVs, and washing machines. However, there are two unusual entries: 'nan' and 'Product', which might indicate missing or placeholder values.
3. Quantity Ordered: The 'Quantity Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some unusual entries such as 'nan' and 'Quantity Ordered', which may indicate missing or placeholder values.
4. Price Each: The 'Price Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some unusual entries such as 'nan' and 'Price Each', which may indicate missing or placeholder values. Additionally, there are some duplicate values in a different format ('600' and '600.0').
5. Order Date: The 'Order Date' column contains the date and time when each order was placed. Entries are in the format 'MM/DD/YY HH:mm'.
6. Purchase Address: The 'Purchase Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to the previous observations, anomalies exist in the 'Product', 'Quantity Ordered', and 'Price Each' columns that need further investigation and cleaning. Additionally, missing values ('nan') and placeholder values ('Product' and 'Quantity Ordered') should be handled appropriately to ensure the accuracy of the dataset.


March

In [ ]:
df_sales_March_2019.dropna(subset=df_sales_March_2019.columns[df_sales_March_2019.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = df_sales_March_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
df_sales_March_2019.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
df_sales_March_2019.drop_duplicates(inplace=True)
df_sales_March_2019.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
df_sales_March_2019.duplicated().sum()

In [ ]:
# Convert 'Order ID' column to numeric, coercing errors to NaN
df_sales_March_2019['Order ID'] = pd.to_numeric(df_sales_March_2019['Order ID'], errors='coerce')

# Convert 'Quantity Ordered' and 'Price Each' columns to numeric
df_sales_March_2019['Quantity Ordered'] = pd.to_numeric(df_sales_March_2019['Quantity Ordered'], errors='coerce')
df_sales_March_2019['Price Each'] = pd.to_numeric(df_sales_March_2019['Price Each'], errors='coerce')

# Convert 'Order Date' column to datetime
df_sales_March_2019['Order Date'] = pd.to_datetime(df_sales_March_2019['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(df_sales_March_2019.dtypes)

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in df_sales_March_2019.columns:
    unique_values = df_sales_March_2019[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in df_sales_March_2019.columns:
    unique_values = df_sales_March_2019[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)


Observations:

1. Order ID: The 'Order ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. It includes a variety of products such as iPhones, charging cables, headphones, monitors, batteries, laptops, TVs, and washing machines. However, there are two unusual entries: 'nan' and 'Product', which might indicate missing or placeholder values.
3. Quantity Ordered: The 'Quantity Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some unusual entries such as 'nan' and 'Quantity Ordered', which may indicate missing or placeholder values.
4. Price Each: The 'Price Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some unusual entries such as 'nan' and 'Price Each', which may indicate missing or placeholder values. Additionally, there are some duplicate values in a different format ('600' and '600.0').
5. Order Date: The 'Order Date' column contains the date and time when each order was placed. Entries are in the format 'MM/DD/YY HH:mm'.
6. Purchase Address: The 'Purchase Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to the previous observations, anomalies exist in the 'Product', 'Quantity Ordered', and 'Price Each' columns that need further investigation and cleaning. Additionally, missing values ('nan') and placeholder values ('Product' and 'Quantity Ordered') should be handled appropriately to ensure the accuracy of the dataset.


April

In [ ]:
df_sales_April_2019.dropna(subset=df_sales_April_2019.columns[df_sales_April_2019.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = df_sales_April_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
df_sales_April_2019.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
df_sales_April_2019.drop_duplicates(inplace=True)
df_sales_April_2019.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
df_sales_April_2019.duplicated().sum()

In [ ]:
# Convert 'Order ID' column to numeric, coercing errors to NaN
df_sales_April_2019['Order ID'] = pd.to_numeric(df_sales_April_2019['Order ID'], errors='coerce')

# Convert 'Quantity Ordered' and 'Price Each' columns to numeric
df_sales_April_2019['Quantity Ordered'] = pd.to_numeric(df_sales_April_2019['Quantity Ordered'], errors='coerce')
df_sales_April_2019['Price Each'] = pd.to_numeric(df_sales_April_2019['Price Each'], errors='coerce')

# Convert 'Order Date' column to datetime
df_sales_April_2019['Order Date'] = pd.to_datetime(df_sales_April_2019['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(df_sales_April_2019.dtypes)

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in df_sales_April_2019.columns:
    unique_values = df_sales_April_2019[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in df_sales_April_2019:
    unique_values = df_sales_April_2019[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)


Observations:

1. Order ID: The 'Order ID' column contains unique numerical identifiers for each order. However, there are some 'nan' values present in this column, indicating missing values.
2. Product: The 'Product' column contains the names of various products sold. Similar to previous observations, there are 'nan' and 'Product' entries, indicating missing or placeholder values.
3. Quantity Ordered: The 'Quantity Ordered' column contains the number of units ordered for each product. Similar to previous observations, there are 'nan' and 'Quantity Ordered' entries, indicating missing or placeholder values.
4. Price Each: The 'Price Each' column contains the price of each product. Similar to previous observations, there are 'nan' and 'Price Each' entries, indicating missing or placeholder values. Additionally, there are some duplicate values in a different format ('600' and '600.0').
5. Order Date: The 'Order Date' column contains the date and time when each order was placed. Similar to previous observations, there are 'nan' entries, indicating missing values.
6. Purchase Address: The 'Purchase Address' column contains the addresses where the purchases were made. Similar to previous observations, there are 'nan' entries, indicating missing values.

As before, the anomalies in the 'Product', 'Quantity Ordered', 'Price Each', 'Order Date', and 'Purchase Address' columns need further investigation and cleaning to ensure the accuracy of the dataset. Additionally, missing values should be handled appropriately to maintain data integrity.

May

In [ ]:
df_sales_May_2019.dropna(subset=df_sales_May_2019.columns[df_sales_May_2019.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = df_sales_May_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
df_sales_May_2019.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
df_sales_May_2019.drop_duplicates(inplace=True)
df_sales_May_2019.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
df_sales_May_2019.duplicated().sum()

In [ ]:
# Convert 'Order ID' column to numeric, coercing errors to NaN
df_sales_May_2019['Order ID'] = pd.to_numeric(df_sales_May_2019['Order ID'], errors='coerce')

# Convert 'Quantity Ordered' and 'Price Each' columns to numeric
df_sales_May_2019['Quantity Ordered'] = pd.to_numeric(df_sales_May_2019['Quantity Ordered'], errors='coerce')
df_sales_May_2019['Price Each'] = pd.to_numeric(df_sales_May_2019['Price Each'], errors='coerce')

# Convert 'Order Date' column to datetime
df_sales_May_2019['Order Date'] = pd.to_datetime(df_sales_May_2019['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(df_sales_May_2019.dtypes)

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in df_sales_May_2019.columns:
    unique_values = df_sales_May_2019[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in df_sales_May_2019:
    unique_values = df_sales_May_2019[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)


Observations:

1. Order ID: The 'Order ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. However, there are two unusual entries: 'nan' and 'Product', which might indicate missing or placeholder values.
3. Quantity Ordered: The 'Quantity Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some unusual entries such as 'nan' and 'Quantity Ordered', which may indicate missing or placeholder values.
4. Price Each: The 'Price Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some unusual entries such as 'nan' and 'Price Each', which may indicate missing or placeholder values. Additionally, there are some duplicate values in a different format ('600' and '600.0').
5. Order Date: The 'Order Date' column contains the date and time when each order was placed. Entries are in the format 'MM/DD/YY HH:mm'.
6. Purchase Address: The 'Purchase Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to the previous observations, anomalies exist in the 'Product', 'Quantity Ordered', and 'Price Each' columns that need further investigation and cleaning. Additionally, missing values ('nan') and placeholder values ('Product' and 'Quantity Ordered') should be handled appropriately to ensure the accuracy of the dataset.

June

In [ ]:
df_sales_June_2019.dropna(subset=df_sales_June_2019.columns[df_sales_June_2019.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = df_sales_June_2019.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
df_sales_June_2019.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
df_sales_June_2019.drop_duplicates(inplace=True)
df_sales_June_2019.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
df_sales_June_2019.duplicated().sum()

In [ ]:
# Convert 'Order ID' column to numeric, coercing errors to NaN
df_sales_June_2019['Order ID'] = pd.to_numeric(df_sales_June_2019['Order ID'], errors='coerce')

# Convert 'Quantity Ordered' and 'Price Each' columns to numeric
df_sales_June_2019['Quantity Ordered'] = pd.to_numeric(df_sales_June_2019['Quantity Ordered'], errors='coerce')
df_sales_June_2019['Price Each'] = pd.to_numeric(df_sales_June_2019['Price Each'], errors='coerce')

# Convert 'Order Date' column to datetime
df_sales_June_2019['Order Date'] = pd.to_datetime(df_sales_June_2019['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(df_sales_June_2019.dtypes)

In [ ]:
# View the column names
df_sales_June_2019.columns

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in df_sales_June_2019:
    unique_values = df_sales_June_2019[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in df_sales_June_2019:
    unique_values = df_sales_June_2019[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order ID: The 'Order ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. However, there are two unusual entries: 'nan' and 'Product', which might indicate missing or placeholder values.
3. Quantity Ordered: The 'Quantity Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some unusual entries such as 'nan' and 'Quantity Ordered', which may indicate missing or placeholder values.
4. Price Each: The 'Price Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some unusual entries such as 'nan' and 'Price Each', which may indicate missing or placeholder values. Additionally, there are some duplicate values in a different format ('600' and '600.0').
5. Order Date: The 'Order Date' column contains the date and time when each order was placed. Entries are in the format 'MM/DD/YY HH:mm'.
6. Purchase Address: The 'Purchase Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to the previous observations, anomalies exist in the 'Product', 'Quantity Ordered', and 'Price Each' columns that need further investigation and cleaning. Additionally, missing values ('nan') and placeholder values ('Product' and 'Quantity Ordered') should be handled appropriately to ensure the accuracy of the dataset.

July

In [ ]:
dap_july.dropna(subset=dap_july.columns[dap_july.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = dap_july.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
dap_july.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
dap_july.drop_duplicates(inplace=True)
dap_july.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
dap_july.duplicated().sum()

In [ ]:
# Define the new column names
new_column_names = {
    'Order_ID': 'Order ID',
    'Quantity_Ordered': 'Quantity Ordered',
    'Price_Each': 'Price Each',
    'Order_Date': 'Order Date',
    'Purchase_Address': 'Purchase Address'
}

# Rename the columns
dap_july.rename(columns=new_column_names, inplace=True)


In [ ]:
# Convert 'Order Date' column to datetime
dap_july['Order Date'] = pd.to_datetime(dap_july['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(dap_july.dtypes)

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in dap_july:
    unique_values = dap_july[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in dap_july.columns:
    unique_values = dap_july[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order_ID: The 'Order_ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. However, there are two unusual entries: 'None' and 'Product', which might indicate missing or placeholder values.
3. Quantity_Ordered: The 'Quantity_Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some missing values (NaN) present.
4. Price_Each: The 'Price_Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some missing values (NaN) present.
5. Order_Date: The 'Order_Date' column contains the date and time when each order was placed. Entries seem to be in datetime format, but there might be some inconsistencies in the date format.
6. Purchase_Address: The 'Purchase_Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

There seem to be some inconsistencies in the data, such as different date formats in the 'Order_Date' column and missing values in the 'Quantity_Ordered' and 'Price_Each' columns. Additionally, the 'Product' column contains 'None' and 'Product' entries, which need to be addressed. Further data cleaning and preprocessing may be necessary to ensure the integrity of the dataset.

In [ ]:
# Fill missing values with a default date (e.g., December 1, 2019)
default_date_jul = pd.to_datetime('2019-07-01', format='%Y-%m-%d')
dap_july['Order Date'] = pd.to_datetime(dap_july['Order Date'], format='%d/%m/%Y %H:%M').fillna(default_date_jul)

In [ ]:
# Checking missing values for First dataset
dap_july.isnull().sum()

August

In [ ]:
dap_august.dropna(subset=dap_august.columns[dap_august.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = dap_august.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
dap_august.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
dap_august.drop_duplicates(inplace=True)
dap_august.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
dap_august.duplicated().sum()

In [ ]:
# Define the new column names
new_column_names = {
    'Order_ID': 'Order ID',
    'Quantity_Ordered': 'Quantity Ordered',
    'Price_Each': 'Price Each',
    'Order_Date': 'Order Date',
    'Purchase_Address': 'Purchase Address'
}

# Rename the columns
dap_august.rename(columns=new_column_names, inplace=True)


In [ ]:
# Convert 'Order Date' column to datetime
dap_august['Order Date'] = pd.to_datetime(dap_august['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(dap_august.dtypes)

In [ ]:
# View the column names
dap_august.columns

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in dap_august.columns:
    unique_values = dap_august[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in dap_august.columns:
    unique_values = dap_august[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order_ID: The 'Order_ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. However, there are two unusual entries: 'None' and 'Product', which might indicate missing or placeholder values.
3. Quantity_Ordered: The 'Quantity_Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some missing values (NaN) present.
4. Price_Each: The 'Price_Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some missing values (NaN) present.
5. Order_Date: The 'Order_Date' column contains the date and time when each order was placed. Entries seem to be in datetime format.
6. Purchase_Address: The 'Purchase_Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

The data seems to have similar issues as before, with missing values in the 'Quantity_Ordered' and 'Price_Each' columns, and inconsistent entries in the 'Product' column. Additionally, there appear to be no missing values in the 'Order_ID', 'Order_Date', and 'Purchase_Address' columns. Further cleaning and preprocessing may be necessary to ensure the integrity of the dataset.

In [ ]:
# Fill missing values with a default date (e.g., December 1, 2019)
default_date_aug = pd.to_datetime('2019-08-01', format='%Y-%m-%d')
dap_august['Order Date'] = pd.to_datetime(dap_august['Order Date'], format='%d/%m/%Y %H:%M').fillna(default_date_aug)

In [ ]:
# Checking missing values for First dataset
dap_august.isnull().sum()

September

In [ ]:
dap_sept.dropna(subset=dap_sept.columns[dap_sept.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = dap_sept.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
dap_sept.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
dap_sept.drop_duplicates(inplace=True)
dap_sept.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
dap_sept.duplicated().sum()

In [ ]:
# Define the new column names
new_column_names = {
    'Order_ID': 'Order ID',
    'Quantity_Ordered': 'Quantity Ordered',
    'Price_Each': 'Price Each',
    'Order_Date': 'Order Date',
    'Purchase_Address': 'Purchase Address'
}

# Rename the columns
dap_sept.rename(columns=new_column_names, inplace=True)


In [ ]:
# Convert 'Order Date' column to datetime
dap_sept['Order Date'] = pd.to_datetime(dap_sept['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(dap_sept.dtypes)

In [ ]:
# View the column names
dap_sept.columns

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in dap_sept:
    unique_values = dap_sept[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in dap_sept.columns:
    unique_values = dap_sept[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order_ID: The 'Order_ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. However, there are two unusual entries: 'None' and 'Product', which might indicate missing or placeholder values.
3. Quantity_Ordered: The 'Quantity_Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some missing values (NaN) present.
4. Price_Each: The 'Price_Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some missing values (NaN) present.
5. Order_Date: The 'Order_Date' column contains the date and time when each order was placed. Entries seem to be in datetime format.
6. Purchase_Address: The 'Purchase_Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to previous observations, the data requires cleaning and preprocessing to address missing values and inconsistent entries in the 'Product' column. The 'Order_ID', 'Order_Date', and 'Purchase_Address' columns seem to have no missing values. Further data cleaning and preprocessing may be necessary to ensure the integrity of the dataset.

In [ ]:
# Fill missing values with a default date (e.g., December 1, 2019)
default_date_sept = pd.to_datetime('2019-09-01', format='%Y-%m-%d')
dap_sept['Order Date'] = pd.to_datetime(dap_sept['Order Date'], format='%d/%m/%Y %H:%M').fillna(default_date_sept)

In [ ]:
# Checking missing values for First dataset
dap_sept.isnull().sum()

October

In [ ]:
dap_oct.dropna(subset=dap_oct.columns[dap_oct.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = dap_oct.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
dap_oct.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
dap_oct.drop_duplicates(inplace=True)
dap_oct.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
dap_oct.duplicated().sum()

In [ ]:
# Define the new column names
new_column_names = {
    'Order_ID': 'Order ID',
    'Quantity_Ordered': 'Quantity Ordered',
    'Price_Each': 'Price Each',
    'Order_Date': 'Order Date',
    'Purchase_Address': 'Purchase Address'
}

# Rename the columns
dap_oct.rename(columns=new_column_names, inplace=True)


In [ ]:
# Convert 'Order Date' column to datetime
dap_oct['Order Date'] = pd.to_datetime(dap_oct['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(dap_oct.dtypes)

In [ ]:
# View the column names
dap_oct.columns

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in dap_oct.columns:
    unique_values = dap_oct[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in dap_oct.columns:
    unique_values = dap_oct[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order_ID: The 'Order_ID' column contains unique numerical identifiers for each order. There are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. However, there are two unusual entries: 'None' and 'Product', which might indicate missing or placeholder values.
3. Quantity_Ordered: The 'Quantity_Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some missing values (NaN) present.
4. Price_Each: The 'Price_Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some missing values (NaN) present.
5. Order_Date: The 'Order_Date' column contains the date and time when each order was placed. Entries seem to be in datetime format.
6. Purchase_Address: The 'Purchase_Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to previous observations, the data requires cleaning and preprocessing to address missing values and inconsistent entries in the 'Product' column. The 'Order_ID', 'Order_Date', and 'Purchase_Address' columns seem to have no missing values. Further data cleaning and preprocessing may be necessary to ensure the integrity of the dataset.

In [ ]:
# Fill missing values with a default date (e.g., December 1, 2019)
default_date_oct = pd.to_datetime('2019-10-01', format='%Y-%m-%d')
dap_oct['Order Date'] = pd.to_datetime(dap_oct['Order Date'], format='%d/%m/%Y %H:%M').fillna(default_date_oct)

In [ ]:
# Checking missing values for First dataset
dap_oct.isnull().sum()

November

In [ ]:
dap_nov.dropna(subset=dap_nov.columns[dap_nov.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = dap_nov.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
dap_nov.isnull().sum()


In [ ]:
# Checking missing values for First dataset
dap_nov.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
dap_nov.drop_duplicates(inplace=True)
dap_nov.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
dap_nov.duplicated().sum()

In [ ]:
# Define the new column names
new_column_names = {
   'Order_ID': 'Order ID',
    'Quantity_Ordered': 'Quantity Ordered',
    'Price_Each': 'Price Each',
    'Order_Date': 'Order Date',
    'Purchase_Address': 'Purchase Address'
}

# Rename the columns
dap_nov.rename(columns=new_column_names, inplace=True)


In [ ]:
# Convert 'Order Date' column to datetime
dap_nov['Order Date'] = pd.to_datetime(dap_nov['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(dap_nov.dtypes)

In [ ]:
# View the column names
dap_nov.columns

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in dap_nov.columns:
    unique_values = dap_nov[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in dap_nov.columns:
    unique_values = dap_nov[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order_ID: The 'Order_ID' column contains unique numerical identifiers for each order, and there are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. There is an entry 'None', which might indicate missing or placeholder values. Additionally, there is an entry 'Product', which seems like a placeholder or a mistake.
3. Quantity_Ordered: The 'Quantity_Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some missing values (NaN) present.
4. Price_Each: The 'Price_Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some missing values (NaN) present.
5. Order_Date: The 'Order_Date' column contains the date and time when each order was placed. Entries seem to be in datetime format.
6. Purchase_Address: The 'Purchase_Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to previous observations, the data requires cleaning and preprocessing to address missing values and inconsistent entries in the 'Product' column. The 'Order_ID', 'Order_Date', and 'Purchase_Address' columns seem to have no missing values. Further data cleaning and preprocessing may be necessary to ensure the integrity of the dataset.

In [ ]:
# Fill missing values with a default date (e.g., December 1, 2019)
default_date_nov = pd.to_datetime('2019-11-01', format='%Y-%m-%d')
dap_nov['Order Date'] = pd.to_datetime(dap_nov['Order Date'], format='%d/%m/%Y %H:%M').fillna(default_date_nov)

In [ ]:
# Checking missing values for First dataset
dap_nov.isnull().sum()

December

In [ ]:
dap_dec.dropna(subset=dap_dec.columns[dap_dec.isnull().any()], how='all', inplace=True)


In [ ]:
completely_empty_rows = dap_dec.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Checking missing values for First dataset
dap_dec.isnull().sum()


In [ ]:
# Drop duplicate rows and reset index inplace
dap_dec.drop_duplicates(inplace=True)
dap_dec.reset_index(drop=True, inplace=True)

In [ ]:
# Count the number of duplicate rows in the DataFrame
dap_dec.duplicated().sum()

In [ ]:
# Define the new column names
new_column_names = {
    'Order_ID': 'Order ID',
    'Quantity_Ordered': 'Quantity Ordered',
    'Price_Each': 'Price Each',
    'Order_Date': 'Order Date',
    'Purchase_Address': 'Purchase Address'
}

# Rename the columns
dap_dec.rename(columns=new_column_names, inplace=True)


In [ ]:
# Convert 'Order Date' column to datetime
dap_dec['Order Date'] = pd.to_datetime(dap_dec['Order Date'], format='%m/%d/%y %H:%M', errors='coerce')


# Now, check the data types after conversion
print(dap_dec.dtypes)

In [ ]:
# View the column names
dap_dec.columns

In [ ]:
# Iterate over columns and print the number of unique values in each column
for column in dap_dec.columns:
    unique_values = dap_dec[column].nunique()
    print(f"Number of unique values in '{column}': {unique_values}")

In [ ]:
# Iterate over columns and view unique values
for column in dap_dec.columns:
    unique_values = dap_dec[column].unique()
    print(f"Unique values in '{column}':")
    print(unique_values)

Observations:

1. Order_ID: The 'Order_ID' column contains unique numerical identifiers for each order, and there are no apparent issues with this column.
2. Product: The 'Product' column contains the names of various products sold. There is an entry 'None', which might indicate missing or placeholder values. Additionally, there is an entry 'Product', which seems like a placeholder or a mistake.
3. Quantity_Ordered: The 'Quantity_Ordered' column contains the number of units ordered for each product. Most entries are numerical values representing quantities, but there are some missing values (NaN) present.
4. Price_Each: The 'Price_Each' column contains the price of each product. Most entries are numerical values representing prices, but there are some missing values (NaN) present.
5. Order_Date: The 'Order_Date' column contains the date and time when each order was placed. Entries seem to be in datetime format.
6. Purchase_Address: The 'Purchase_Address' column contains the addresses where the purchases were made. Each entry includes the street address, city, state, and ZIP code.

Similar to previous observations, the data requires cleaning and preprocessing to address missing values and inconsistent entries in the 'Product' column. The 'Order_ID', 'Order_Date', and 'Purchase_Address' columns seem to have no missing values. Further data cleaning and preprocessing may be necessary to ensure the integrity of the dataset.

In [ ]:
# Fill missing values with a default date (e.g., December 1, 2019)
default_date_dec = pd.to_datetime('2019-12-01', format='%Y-%m-%d')
dap_dec['Order Date'] = pd.to_datetime(dap_dec['Order Date'], format='%d/%m/%Y %H:%M').fillna(default_date_dec)

In [ ]:
# Checking missing values for First dataset
dap_dec.isnull().sum()

### COMBINING DATASETS

SQL Dataset combined

In [ ]:
dap_combined = pd.concat([dap_july, dap_august,dap_sept,dap_oct,dap_nov,dap_dec], ignore_index=True)

In [ ]:
dap_combined.info()

Combine all datasets

In [ ]:
# Redefine sales_data using your actual DataFrame
sales_data = pd.concat([df_sales_January_2019, df_sales_February_2019, df_sales_March_2019, df_sales_April_2019, df_sales_May_2019, df_sales_June_2019, dap_combined],ignore_index=True)
#dap_july, dap_august, dap_sept, dap_oct, dap_nov, dap_dec

# Define a dictionary mapping each product to its category
product_category_mapping = {
    'Macbook Pro Laptop': 'Electronics',
    'LG Washing Machine': 'Electronics',
    '27in FHD Monitor': 'Electronics',
    'ThinkPad Laptop': 'Electronics',
    'Google Phone': 'Electronics',
    'Apple Airpods Headphones': 'Electronics',
    'Vareebadd Phone': 'Electronics',
    'iPhone': 'Electronics',
    '20in Monitor': 'Electronics',
    '34in Ultrawide Monitor': 'Electronics',
    '27in 4K Gaming Monitor': 'Electronics',
    'LG Dryer': 'Electronics',
    'USB-C Charging Cable': 'Accessories',
    'AA Batteries (4-pack)': 'Accessories',
    'Bose SoundSport Headphones': 'Accessories',
    'AAA Batteries (4-pack)': 'Accessories',
    'Lightning Charging Cable': 'Accessories',
    'Wired Headphones': 'Accessories',
    'Flatscreen TV': 'Electronics',
    'Product': 'Others',
    None: 'Others'
}

# Create a new column 'Product Category' by mapping the 'Product' column using the dictionary
sales_data['Product Category'] = sales_data['Product'].map(product_category_mapping)


In [ ]:
sales_data.info()

In [ ]:
sales_data.head()

In [ ]:
sales_data.info()

In [ ]:
# Display summary statistics for Concatenated dataset
sales_data.describe()

In [ ]:
sales_data.isnull().sum()

In [ ]:
sales_data.duplicated().sum()

In [ ]:
# Drop Duplicate Rows
sales_data.drop_duplicates(inplace=True)

In [ ]:
sales_data.duplicated().sum()

In [ ]:
completely_empty_rows = dap_dec.isnull().all(axis=1)

# Step 2: Sum the boolean values indicating completely empty rows
sum_completely_empty_rows = completely_empty_rows.sum()

# Step 3: Print the total number of completely empty rows
print("Total completely empty rows:", sum_completely_empty_rows)

In [ ]:
# Drop rows with any missing values
sales_data.dropna(inplace=True)


In [ ]:
sales_data.isnull().sum()

In [ ]:
#drop customer ID.
del sales_data['Order ID']

In [ ]:
sales_data.describe()

In [ ]:
sales_data.info()

In [ ]:
#save concat sales_data to CSV for visualisation
sales_data.to_csv('sales_data.csv', index=False)

### 1. <b> Univariate Data analysis

In [ ]:
# Visualizing the distribution of Numerical Variables
sales_data.hist(figsize=(12,8), grid= False)
plt.show()

1. The most frequent quantity ordered 1.
2. The most frequent price of each product is between 0-200

In general, there seems to be no correlation between the quantity ordered and the price per order. There are expensive orders for small quantities and cheap orders for large quantities.



In [ ]:
# Create a single boxplot to show outliers
cols = [ 'Quantity Ordered', 'Price Each']

fig, ax = plt.subplots(figsize=(14, 8))
sns.boxplot(data=sales_data[cols], whis=1.5, orient='h', palette=['skyblue', 'limegreen'])
plt.title("Boxplot of Numerical Features with Outliers")
plt.show()

In [ ]:
#Plot KDEs(kernel density estimation) for all columns
fig, axes = plt.subplots(nrows=len(cols), figsize=(12, 20))
for i, col in enumerate(cols):
    sns.kdeplot(data=sales_data, x=col, ax=axes[i], fill=True)
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Density')
   
    # Calculate mean, skewness, and kurtosis
    mean_val = sales_data[col].mean()
    skewness_val = sales_data[col].skew()
    kurtosis_val = sales_data[col].kurtosis()
   
    # Add mean, skewness, and kurtosis as text annotations
    axes[i].text(0.6, 0.9, f'Mean: {mean_val:.2f}', transform=axes[i].transAxes)
    axes[i].text(0.6, 0.8, f'Skewness: {skewness_val:.2f}', transform=axes[i].transAxes)
    axes[i].text(0.6, 0.7, f'Kurtosis: {kurtosis_val:.2f}', transform=axes[i].transAxes)
   
    # Add mean line
    axes[i].axvline(mean_val, color='red', linestyle='--', label='Mean')
   
    # Add red dots to indicate potential outliers
    outliers = sales_data[(sales_data[col] > mean_val + 3 * sales_data[col].std()) | (sales_data[col] < mean_val - 3 * sales_data[col].std())]
    axes[i].plot(outliers[col], [0] * len(outliers), 'ro', label='Potential Outliers')
   
    # Add legend
    axes[i].legend()
   
plt.tight_layout()
plt.show()

observations:
1. the quantity ordered has a skweness of 4.83, so it suggests a positive skewness.The distribution  is heavily skewed towards higher values, with a long tail on the right side.
2. The price data exhibits significant positive skewness and high kurtosis, indicating a distribution that is highly right-skewed with heavy tails and a sharp peak around the mean price. This suggests that while most prices are clustered around the mean, there are notable outliers or extreme values at both ends of the price spectrum

### 2. <b> Bivariate Data analysis

In [ ]:
product_quantity = sales_data.groupby('Product')['Quantity Ordered'].sum().sort_values(ascending=False)
product_quantity.plot(kind='barh', figsize=(10, 6))  # Changing the plot type to 'barh' for horizontal bar plot
plt.title('Total Quantity Ordered for Each Product')
plt.xlabel('Total Quantity Ordered')
plt.ylabel('Product')
plt.show()



From this chart, we can observe that the AAA Batteries (4-pack) are the most ordered product, with a total quantity that appears to be just shy of 30,000. The next most ordered product is the AA Batteries (4-pack), followed by the USB-C Charging Cable and the Lightning Charging Cable. These items are typically consumable or commonly used accessories, which may explain their higher order quantities.

On the other end of the spectrum, the least ordered products are the LG Dryer and the LG Washing Machine. This could be due to several factors, such as higher prices, lower purchase frequency, or less demand compared to smaller electronic accessories.

A notable observation from the mid-range of the product order quantities is that personal electronics like the MacBook Pro Laptop, ThinkPad Laptop, and various types of phones and monitors have a moderate level of orders, indicating a steady but lower demand compared to the cheaper, more consumable products.

Overall, the chart indicates a trend where lower-cost and frequently used items have higher order volumes, while more expensive and durable goods have lower order volumes. This pattern is typical in consumer electronics markets where small accessories are purchased more frequently than large appliances or high-end electronics.

In [ ]:
# Product and Price Each
product_price = sales_data.groupby('Product')['Price Each'].mean().sort_values(ascending=False)
product_price.plot(kind='barh', figsize=(10, 6))
plt.title('Average Price for Each Product')
plt.xlabel('Product')
plt.ylabel('Average Price')
plt.xticks(rotation=45)
plt.show()

Here are a few observations from the chart above:

Product Price Range: There is a wide range of average prices among the products displayed. The lowest average price products are the AAA and AA batteries, while the highest average price is attributed to the MacBook Pro Laptop.

Grouping by Price: The products seem to group into distinct categories based on their average price. Small accessories like batteries and charging cables are at the lower end, personal audio and monitors are in the middle range, while major appliances and high-end electronics like the MacBook Pro and iPhone are at the higher end.

Variability in Price: There is significant variability in the average price of products, indicating a diverse set of items with different value propositions and target markets. For instance, the average price of a MacBook Pro Laptop is substantially higher than any other product on the list, which suggests it is likely a high-end product with premium features and branding.

Comparison of Similar Products: Within similar product categories, there is a range of average prices that could reflect different brand values, features, or specifications. For example, the Apple Airpods Headphones have a higher average price compared to other audio products like the Bose SoundSport Headphones or Wired Headphones, indicating brand value or feature differences.

Tech Product Categories: The graph covers a broad spectrum of tech product categories from simple consumables to complex electronics, which might be used to analyze market trends, consumer spending, or to inform stocking decisions for retailers.

In [ ]:
# Hexbin plot
plt.figure(figsize=(10, 6))
plt.hexbin(sales_data['Price Each'], sales_data['Quantity Ordered'], gridsize=20, cmap='YlGnBu', edgecolors='k')
plt.colorbar(label='count in bin')
plt.title('Hexbin Plot of Quantity Ordered vs. Price Each')
plt.xlabel('Price Each')
plt.ylabel('Quantity Ordered')
plt.grid(True)
plt.show()


Distribution of Orders:
The majority of orders fall into the lower price range, as indicated by the concentration of darker hexbins in the lower left corner.
These darker hexbins represent higher counts of orders for items with lower prices.
Price and Quantity Relationship:
As the price each decreases, there is a trend of increased quantity ordered.
This suggests that customers are more likely to order larger quantities when the price per item is lower.
Sparse Areas:
Most hexbins are light-colored, indicating low counts.
There are fewer orders for items with higher prices.
Overall Trend:
The graph shows that quantity ordered tends to be higher for lower-priced items.

### <b> Multivariate Analysis

In [ ]:
# Select only numerical columns
numerical_columns = sales_data.select_dtypes(include=['float64', 'int64'])

# Compute the correlation matrix
correlation_matrix = numerical_columns.corr()

# Plot the correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()


The heat map represents a correlation matrix between two variables: “Quantity Ordered” (on the y-axis) and “Price Each” (on the x-axis).
The color scale ranges from blue (negative correlation) to red (positive correlation).

Key observations:
There is a perfect positive correlation of 1.00 between “Quantity Ordered” and itself (indicated by the red square in the top left corner).
Similarly, there is a perfect positive correlation of 1.00 between “Price Each” and itself (shown by the red square in the bottom right corner).
However, there is a weak negative correlation of approximately -0.15 between “Quantity Ordered” and “Price Each” (represented by the blue square in the top right corner).

Interpretation:
When “Quantity Ordered” increases, there is a corresponding increase in “Price Each” (positive correlation).
The weak negative correlation suggests that as “Quantity Ordered” goes up, there is a slight decrease in the unit price (“Price Each”).

Practical Implications:
Businesses can use this information to optimize pricing strategies.
Understanding the relationship between quantity and price helps in decision-making, inventory management, and revenue forecasting.

In [ ]:
# Pairplot
sns.pairplot(sales_data, height=4)
plt.suptitle('Pairplot of Numerical Variables', y=1.02)
plt.show()


Pairplot Overview:

The plot displays a pairplot of two numerical variables: “Quantity Ordered” and “Price Each.”
The diagonal contains histograms for each variable, while the off-diagonal cells show scatter plots.
The x-axis labels represent “Quantity Ordered,” and the y-axis labels represent “Price Each.”

Histograms:

Quantity Ordered: The histogram for quantity ordered shows a significant spike at lower quantities. Most orders appear to be for small quantities.
Price Each: The histogram for price each does not reveal a clear pattern or trend. Prices vary widely.

Scatter Plots:

There is no strong linear correlation between “Quantity Ordered” and “Price Each.” The scatter plots do not exhibit any distinct trend.
The data points are scattered across the plot, indicating that the relationship between these variables is not straightforward.

 ## **The Hypothesis**

 **Null Hypothesis:** There is no difference in revenue generated between different product categories.
  
  **Alternative Hypothesis:** Certain product categories generate significantly more revenue compared to others.

In [ ]:
# Calculate revenue
sales_data['Revenue'] = sales_data['Quantity Ordered'] * sales_data['Price Each']

# Extract revenue for each product category
electronics_revenue = sales_data[sales_data['Product Category'] == 'Electronics']['Revenue']
accessories_revenue = sales_data[sales_data['Product Category'] == 'Accessories']['Revenue']
others_revenue = sales_data[sales_data['Product Category'] == 'Others']['Revenue']

# Perform ANOVA test
statistic, p_value = f_oneway(electronics_revenue, accessories_revenue, others_revenue)

# Define significance level
alpha = 0.05

# Interpret the result
if p_value < alpha:
    print("Reject the null hypothesis.")
    print("Certain product categories generate significantly more revenue compared to others.")
else:
    print("Fail to reject the null hypothesis.")
    print("There is no difference in revenue generated between different product categories.")


## **The Analytical Questions**

1. How much money did we make this year? 

2. Can we identify any seasonality in the  sales? 

3. What are our best and worst-selling products? 

4. How do sales compare to previous months or weeks? 

5. Which cities are our products delivered to most? 

6. How do product categories compare in revenue generated and quantities  ordered? 

7. What are the best and worst-selling products?

1. How much money did we make this year? 

In [ ]:
# Calculate revenue for each transaction
sales_data['Revenue'] = sales_data['Quantity Ordered'] * sales_data['Price Each']

# Sum up the revenue column to calculate total revenue
total_revenue = sales_data['Revenue'].sum()

# Print the total revenue
print("Total revenue generated this year:", total_revenue)


Based on the data available, the total revenue generated this year amounts to $34.57 million. This substantial revenue reflects the combined impact of both the “Accessories” and “Electronics” product categories. It’s essential to continue monitoring these trends to inform strategic decisions and optimize sales performance

2. Can we identify any seasonality in the  sales? 

In [ ]:
sales_data_2019 = sales_data[sales_data['Order Date'].dt.year == 2019].copy()

# Extract the month from the 'Order Date' column and assign it to a new column 'Order Month'
sales_data_2019.loc[:, 'Order Month'] = sales_data_2019['Order Date'].dt.month

# Group the sales data by month and sum the sales
monthly_sales_2019 = sales_data_2019.groupby('Order Month')['Quantity Ordered'].sum()

# Reindex the monthly_sales_2019 DataFrame to include all 12 months
monthly_sales_2019 = monthly_sales_2019.reindex(range(1, 13), fill_value=0)


# Plot the monthly sales data for the year 2019
monthly_sales_2019.plot(kind='line', figsize=(10, 6), marker='o', color='b', linestyle='-')
plt.title('Monthly Sales in 2019')
plt.xlabel('Month')
plt.ylabel('Total Quantity Ordered')
plt.xticks(monthly_sales_2019.index, ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.show()

1. **Seasonality Overview**:
   - The line graph titled "Monthly Sales in 2019" reveals patterns that suggest **seasonal fluctuations**.
   - Sales exhibit recurring cycles throughout the year.

2. **Monthly Trends**:
   - **March**: Sales peak at over 20,000.
   - **May and June**: There is a noticeable dip, reaching its lowest point at approximately 12,500.
   - **July to December**: Sales gradually increase, with another significant peak in December (approximately 27,500).

3. **Interpretation**:
   - The upward trend from July to December aligns with the **holiday season**, indicating strong sales during this period.
   - The cyclic behavior suggests that sales are influenced by **seasonal factors**.

In summary, the sales data exhibits seasonality, with notable peaks around March and December. Understanding these patterns can inform business strategies and forecasting efforts.


3. What are our best and worst-selling products?

In [ ]:
# Group the sales data by product and sum the quantity ordered for each product
product_sales = sales_data.groupby('Product')['Quantity Ordered'].sum()

# Sort the products based on total quantity ordered in descending order
product_sales_sorted = product_sales.sort_values(ascending=False)

# Best-selling product (product with the highest quantity ordered)
best_selling_product = product_sales_sorted.index[0]

# Worst-selling product (product with the lowest quantity ordered)
worst_selling_product = product_sales_sorted.index[-1]

print("Best-selling product:", best_selling_product)
print("Worst-selling product:", worst_selling_product)


The main factor that can be attributed to the observation above is:

**Utility and Frequency of Use**: AAA batteries are commonly used in many household items such as remote controls, toys, flashlights, etc. They are consumable goods, meaning people need to regularly replace them. On the other hand, a dryer is a large appliance that people typically purchase infrequently and expect to last for several years without needing replacement.

Other factors include:

**Seasonal Variations**: The demand for AAA batteries might be relatively consistent throughout the year, whereas the demand for dryers could fluctuate based on factors like seasons (e.g., more people buying dryers during colder, wetter months).

**Price Sensitivity and Disposable Income**: AAA batteries are generally inexpensive and considered essential items for many households, making them an easy and frequent purchase. Dryers, on the other hand, are larger investments that require more consideration and planning, especially if they're high-end models.



In [ ]:
# Plot the quantity ordered for each product
plt.figure(figsize=(10, 6))
product_sales_sorted.plot(kind='barh')
plt.title('Quantity Ordered for Each Product')
plt.xlabel('Product')
plt.ylabel('Total Quantity Ordered')
plt.xticks(rotation=45)
plt.show()

4. How do sales compare to previous months or weeks? 

In [ ]:
# Filter data for the year 2019
sales_data_2019 = sales_data[sales_data['Order Date'].dt.year == 2019].copy()

# Calculate revenue for each transaction
sales_data_2019['Revenue'] = sales_data_2019['Quantity Ordered'] * sales_data_2019['Price Each']

# Group by month and sum up the revenue for each month
monthly_revenue = sales_data_2019.groupby(sales_data_2019['Order Date'].dt.to_period('M'))['Revenue'].sum()

# Reset index to convert the grouped data back to a DataFrame
monthly_revenue = monthly_revenue.reset_index()

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(monthly_revenue['Order Date'].astype(str), monthly_revenue['Revenue'], marker='o', linestyle='-')
plt.title('Monthly Revenue Trend in 2019')
plt.xlabel('Month')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

comparing sales to previous months:

January to July Decline:
From January to July, sales gradually decreased.
The lowest point was in July (around 2.5 million in revenue).

August to October Stability:

In August, there was a slight increase in sales.
Sales remained relatively stable from August to October.

November and December Surge:

The most significant change occurred from October to December.
Sales skyrocketed, reaching their peak in December (close to 4.5 million in revenue).

In summary, sales experienced a seasonal surge towards the end of the year, likely influenced by holiday shopping. The upward trend in November and December suggests successful year-end sales efforts.

5. Which cities are our products delivered to most? 

In [ ]:
# Extract city information from 'Purchase Address'
sales_data['City'] = sales_data['Purchase Address'].apply(lambda x: x.split(',')[1])

# Count the occurrences of each city
city_counts = sales_data['City'].value_counts()

# Now you can identify the cities where our products are delivered to most
print("Top 5 cities where our products are delivered to most:")
print(city_counts.head())

The observation regarding product deliveries indicates that San Francisco has the highest volume of deliveries, with a count of 20,506. Following San Francisco, Los Angeles and New York City also exhibit substantial delivery volumes, with 13,665 and 11,357 deliveries, respectively. Additionally, Boston and Atlanta demonstrate significant delivery numbers, with 9,044 and 6,868 deliveries, respectively. These figures suggest a concentration of product distribution in major urban centers, particularly in San Francisco, Los Angeles, and New York City. Understanding these delivery patterns can help in strategic planning, resource allocation, and targeted marketing efforts to maximize sales potential in these key metropolitan areas.

In [ ]:
# Plotting the top cities for 2019
plt.figure(figsize=(10, 6))
city_counts.head().plot(kind='bar', color='skyblue')
plt.title('Top Cities for Product Deliveries in 2019')
plt.xlabel('City')
plt.ylabel('Number of Deliveries')
plt.xticks(rotation=45)
plt.show()

6. How do product categories compare in revenue generated and quantities  ordered? 

In [ ]:
# Group the sales data by product category and calculate total revenue and quantity ordered
category_comparison = sales_data.groupby('Product Category').agg({'Revenue': 'sum', 'Quantity Ordered': 'sum'})

# Plot the comparison
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# Revenue comparison
ax[0].bar(category_comparison.index, category_comparison['Revenue'], color='skyblue')
ax[0].set_title('Revenue Generated by Product Category')
ax[0].set_xlabel('Product Category')
ax[0].set_ylabel('Total Revenue')

# Quantity ordered comparison
ax[1].bar(category_comparison.index, category_comparison['Quantity Ordered'], color='salmon')
ax[1].set_title('Quantities Ordered by Product Category')
ax[1].set_xlabel('Product Category')
ax[1].set_ylabel('Total Quantity Ordered')

plt.tight_layout()
plt.show()

1. Revenue by Product Category:
The graph on the left shows the revenue generated by two product categories: “Accessories” and “Electronics.”
The “Electronics” category has significantly higher revenue compared to “Accessories.”
This suggests that electronics products contribute more to overall revenue.
2. Quantities Ordered by Product Category:
The graph on the right displays the quantities ordered for the same product categories.
Interestingly, “Accessories” have a higher quantity ordered compared to “Electronics.”
Despite lower revenue, accessories seem to be more popular in terms of the number of orders.
In summary, while electronics generate substantial revenue, accessories attract more customers in terms of quantity ordered. This information could be valuable for decision-making and business strategy

7. Are there any price ranges that attract more customers?

In [ ]:
plt.figure(figsize=(10, 6))
plt.hist(sales_data['Price Each'], bins=20, color='skyblue', edgecolor='black')
plt.title('Price Ranges vs Quantity of Orders')
plt.xlabel('Price')
plt.ylabel('Quantity of Orders')
plt.grid(False)  
plt.show()

1. Distribution of Orders by Price Range:
The majority of orders fall within the 0-250 price range, as indicated by the very tall bar. Nearly 100,000 orders were placed in this range.
As the price range increases, the quantity of orders decreases significantly.
2. Decreasing Order Volume with Higher Prices:
The shorter bars represent higher price ranges (250-500, 500-750, etc.). These ranges have significantly fewer orders.
The trend suggests that customers are more likely to make purchases for products priced below 250 dollars.
3. Business Implications:
To drive sales, consider focusing on products within the lower price range, as they attract the highest order volume.
For higher-priced items, targeted marketing efforts or promotions may be necessary to boost sales.

## **Conclusion**

1. Product Deliveries by City:
San Francisco leads with the highest volume of deliveries (20,506).
Los Angeles and New York City follow closely with 13,665 and 11,357 deliveries, respectively.
Boston and Atlanta also demonstrate significant delivery numbers (9,044 and 6,868, respectively).
Concentration in major urban centers (San Francisco, Los Angeles, and New York City) suggests strategic planning opportunities for resource allocation and targeted marketing efforts
2. Revenue by Product Category:
The graph on the left shows revenue generated by two product categories: “Accessories” and “Electronics.”
“Electronics” significantly outperforms “Accessories” in terms of revenue.
This indicates that electronics products contribute more to overall revenue.
3. Quantities Ordered by Product Category:
The graph on the right displays quantities ordered for the same product categories.
Interestingly, “Accessories” have a higher quantity ordered compared to “Electronics.”
Despite lower revenue, accessories seem to be more popular in terms of the number of orders.
4. Distribution of Orders by Price Range:
The majority of orders fall within the 0-250 price range, as indicated by the very tall bar. Nearly 100,000 orders were placed in this range.
As the price range increases, the quantity of orders decreases significantly.
The shorter bars represent higher price ranges (250-500, 500-750, etc.), which have significantly fewer orders.

In conclusion, while electronics generate substantial revenue, accessories attract more customers in terms of quantity ordered. Understanding these patterns can inform decision-making and business strategy. 📊💡




